sartography/protocol-builder-mock

templates/form.html, templates/index.html, tests/test_sanity.py
{{ base_href }} needed quotes around it.
Fixed my test for LDAP search so it doesn't have localhost hardcoded :(
=> fix for user lookup stuff.

pb/__init__.py, templates/index.html
- changed onclick to onchange for the select tag
- added BASE_HREF to the redirect url
=> Two bug fixes:

config/testing.py, migrations/versions/277f05065db0_.py, migrations/versions/c14ddab2e6ca_.py, pb/__init__.py, pb/api.py, pb/api.yml, pb/forms.py, pb/models.py, tests/test_sanity.py
Added irb_info data to PB Mock
Added new irb_info table with relationship to study
Added form, route, and method to update this data
Added migration for new table
Moved API endpoint code to separate file
Added API endpoint to access new irb_info data
Added missing test for deleting a study
Fixed test for study_details
=> Irb pro api endpoints #275

tests/test_sanity.py
… test database.
These tests failed in SQLite.
Modified test_delete_study to ensure existence of data we later delete.
Added test_update_study_from_csv which failed because of issue between SQLite and csv file data
=> Update pb mock tests #359

pb/routes.py
If not, don't seed data to the form.
=> Make sure our db query returned a result.

templates/index.html
Another URL issue after pushing code to testing.
=> Possible fix for URL error on testing.

migrations/versions/42d973f2723f_.py, pb/api.yml, pb/forms.py, pb/models.py, pb/pb_mock.py
=> remove hsr number from study edit #418

pb/models.py, tests/test_sanity.py
Added new events and status to the irb_info page
Include the event and status IDs in the API endpoint
=> Irb events and status #427

migrations/versions/d6627c76ed75_.py, pb/api.py, pb/forms.py, pb/models.py, pb/pb_mock.py, pb/routes.py
Changes to line up with UVA PB
Biggest change is how required_documents works.
=> Test production #519

pb/api.py, pb/models.py
We didn't return a valid response from required_documents
This solution is *much* simpler
=> Fixed bug in required_documents #519

pb/api.py, pb/models.py
Modifications for the new `StudyCreator` endpoint at UVA PB.
=> User studies endpoint #561

.travis.yml, pb/models.py
Added a new document to Required Documents
=> Add Gene Therapy doc #686

pb/forms.py, pb/routes.py
Remove review types 23, 24
Add review type 21
=> Update Review Types #692

pb/forms.py
Change Event and Status labels
Include IDs indropdowns
=> IRB Info updates #693

pb/models.py
=> Add IRB Info event #712

pb/models.py
Just added a new status and a new event for the IRB Info page
=> New IRB Info status and event #718

pb/models.py
=> Add new IRB Info event #727

config/default.py, migrations/versions/2a10c0990574_open_to_enrollment_replacement.py, pb/models.py, tests/test_sanity.py
Changed the text for IRB_STATUS to "Open to Enrollment"
Includes a migration to update the DB
=> Bug/irb status update #763

pb/models.py
Merge changes to document list in models.py.
=> Merge changes to document list in models.py.

.github/workflows/constraints.txt
Local version of poetry changed lock file version.
=> update version of poetry
